download_libs downloader using wget2
openframeworks/openFrameworks pull request #7907
Opened 2024-03-10 16:37 UTC by dimitre

So all files can be downloaded faster, in parallel
if wget2 is installed locally
if not it will fallback to curl, then wget
cc @danoli3

2024-03-11 04:37 UTC, danoli3 commented
Nice1!

On Mon, 11 Mar 2024 at 3:38 AM, Dimitre ***@***.***> wrote:

> So all files can be downloaded faster, in parallel
> if wget2 is installed locally
> if not it will fallback to curl, then wget
> cc @danoli3 <https://github.com/danoli3>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/openframeworks/openFrameworks/pull/7907
> Commit Summary
>
>    - 6e8819c
>    <https://github.com/openframeworks/openFrameworks/pull/7907/commits/6e8819c740a8d66f4762801530e180acb56799f3>
>    downloader in parallel
>    - 2391c4f
>    <https://github.com/openframeworks/openFrameworks/pull/7907/commits/2391c4ff62f1f6d003b0492c7257ba4b82692062>
>    Update download_libs.sh - parallel downloads
>
> File Changes
>
> (2 files
> <https://github.com/openframeworks/openFrameworks/pull/7907/files>)
>
>    - *M* scripts/dev/download_libs.sh
>    <https://github.com/openframeworks/openFrameworks/pull/7907/files#diff-96d87311de09ce27303e894d36ca9489c7f1da1c402f42b46c0f1a1c8daf1b88>
>    (24)
>    - *M* scripts/dev/downloader.sh
>    <https://github.com/openframeworks/openFrameworks/pull/7907/files#diff-ecd23008f66130682c16b57cfb43f866f4b1be9076f3231f7f3489768211e0ef>
>    (41)
>
> Patch Links:
>
>    - https://github.com/openframeworks/openFrameworks/pull/7907.patch
>    - https://github.com/openframeworks/openFrameworks/pull/7907.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openframeworks/openFrameworks/pull/7907>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGK2HHPMVSHLM34KOKIH43YXSD67AVCNFSM6AAAAABEPDFLLSVHI2DSMVQWIX3LMV43ASLTON2WKOZSGE3TONZZHAZDMMA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-12 00:40 UTC, dimitre commented
I think it is finally passing tests. I've simplified the functions to invoke the downloader, so multiple files can be passed easily. wget2 and curl download faster in parallel, wget download in series.

2024-05-16 03:04 UTC, ofTheo commented
@dimitre if this is good to merge - looks good to me :)

2024-05-16 04:22 UTC, danoli3 requested changes

2024-05-16 04:22 UTC, danoli3 commented on scripts/dev/download_libs.sh
> +if command -v wget2 2>/dev/null; then
Should just do this in downloader 
https://github.com/openframeworks/openFrameworks/blob/master/scripts/dev/downloader.sh#L25

2024-05-16 04:22 UTC, danoli3 commented on scripts/msys2/buildAllExamples.sh
do we need 755 
"755 means you can do anything with the file or directory, and other users can read and execute it but not alter it. Suitable for programs and directories you want to make publicly available. 644 means you can read and write and execute the file or directory and other users can only read it"

2024-05-16 04:22 UTC, danoli3 commented on scripts/dev/download_libs.sh
> +if command -v wget2 2>/dev/null; then
if wget2, else curl, else wget 
```
if command -v wget2 2>/dev/null; then 
        wget2 $@ 2> /dev/null;
elif command -v curl 2>/dev/null; then 
        curl -LO --retry 20 -O -s $@; 
else 
        wget -q $@ 2> /dev/null; 
fi
```

2024-05-16 16:05 UTC, dimitre commented on scripts/msys2/buildAllExamples.sh
reverting this one. I've used chmod +x to execute on my system, to test some stuff on macOS from msys2 scripts

2024-05-29 19:56 UTC, dimitre commented
Closing this in favor of https://github.com/openframeworks/openFrameworks/pull/8002

2024-05-29 19:56 UTC, closed without merging