Thick Lines and Varying Point Sizes for Programmable Renderer
openframeworks/openFrameworks pull request #8019
Opened 2024-06-14 04:39 UTC by NickHardeman

This PR attempts to mimic some of the original line and point drawing functionality allowed by earlier versions of GL for the Programmable GL Renderer pipeline while introducing some simple additional functionality. 

### Lines
This PR aims to enable varying line width for the following:
- ofMesh with mode  GL_LINES, GL_LINE_STRIP or GL_LINE_LOOP
- ofPolyline
- ofPath ( which draws the poly lines and sets the width from the stroke width on the path )
- ofDrawLine(x,y)

Currently supported attributes:
- Color per line point
- Textures (y coord is 0 -> tex height ) 
- Global color

The approach for the thick lines involves adding additional points per vertex to a vbo mesh that feeds additional VAO attributes to a shader.
- Allows for referencing next and previous vertex references
- Does not require a geometry shader ( not available in all instances or platforms ) 
- Renders 4 vertices per source vertex for mitered lines (GL_LINE_STRIP, GL_LINE_LOOP) and 2 vertices for GL_LINES 
- Can set screen space width (pixel width) regardless of distance to camera or world width ( size attenuation )

This PR currently does not intend to do the following
- Add end caps, round or otherwise
- Address self intersection

Example Code:

```
path.setStrokeWidth(mLineWidth);
path.draw();
```

```
ofSetLineWidth(mLineWidth);
mesh.setMode(OF_PRIMITIVE_LINES);
mesh.draw();
```

### Points
Points can vary in size based of a newly introduced function `ofSetPointSize(pointSize);` 
Supports
- Per point color
- Textures ( single texture for all points )
- Smoothing via a shader 

Example code:
```
ofSetPointSize(pointSize);
ofEnablePointSprites();
texture.bind();
mesh.drawVertices();
texture.unbind();
```

**_Core functionality to the GL Programmable Renderer has been changed and thus requires extensive testing._** 

**TODO:**
- Optimizations
- Thorough testing
- Cleaning up and comments

![Screenshot 2024-06-13 at 10 53 04 PM](https://github.com/openframeworks/openFrameworks/assets/142694/ed06ba68-07df-43cc-92b6-5602b696012b)

2024-06-14 15:35 UTC, dimitre commented
Wowww marvellous work @NickHardeman

2024-06-14 15:39 UTC, ofTheo commented
Yay! Wow, nice work @NickHardeman!

2024-06-20 14:52 UTC, NickHardeman commented
This PR will close #8021

2024-06-21 01:34 UTC, NickHardeman commented
When drawing an ofPolyline and a texture is bound, the tex coords get added so that the first point has texcoord.x == 0.0 and the last point has texcoord.x == texture.width. 
The y coord gets set between 0 and texture height based on the side of the line the dynamic points get added ( for poly lines and meshes ).
_**Should there be a way to control the texture coordinates for an ofPolyline?**_

![Screenshot 2024-06-20 at 9 30 26 PM](https://github.com/openframeworks/openFrameworks/assets/142694/6fbbbd1c-720e-499f-8dbb-a578c4def6fb)

2024-06-21 01:38 UTC, NickHardeman commented
Without changing the vertices of miters, they can look like it does below, here they are clamped, but it doesn't look right with smaller angles between lines. Notice the colored lines.
![Screenshot 2024-06-19 at 10 57 33 PM](https://github.com/openframeworks/openFrameworks/assets/142694/672855e9-9bc5-410e-8397-47c9af4c0762)

2024-06-25 02:02 UTC, NickHardeman commented
Some relevant discussions:
https://github.com/openframeworks/openFrameworks/issues/730
https://github.com/openframeworks/openFrameworks/issues/7689
Fixes #3460

2024-06-26 15:35 UTC, danoli3 commented on libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp
> +	setColor(style.color.r, style.color.g, style.color.b, style.color.a);
nice

2024-06-26 15:38 UTC, danoli3 commented on libs/openFrameworks/gl/ofGLProgrammableRenderer.h
> +	std::unordered_map<GLuint, std::shared_ptr<ShaderCollection> > mDefaultShadersMap;
cool idea

2024-06-26 15:38 UTC, danoli3 requested changes
Amazing, yeah just rebase onto latest master and lets check ci

2024-06-27 01:23 UTC, NickHardeman commented
Thank you @danoli3. I can update next week when I am back at a computer 😀

2024-07-09 15:17 UTC, danoli3 commented
Wicked, we should just take a bunch of snapshots of gl / visual examples first draw frame:
- pre 
- with changes

2024-07-09 15:26 UTC, ofTheo approved these changes

2024-07-09 23:03 UTC, ofTheo commented
I'd be good to merge this now - so we can get it in front of people. 
Especially as it's fixing something that didn't work before.

2024-07-10 05:14 UTC, danoli3 commented
I'm just running a regression comparer on this and then good to merge! So far collected images Pre

Just building opencv quality comparer for some analysis, saw opencv missing contrib modules, adding them now to build scripts 

I'll add comparer project to dev projects

2024-07-10 12:13 UTC, danoli3 commented
Looks good though overall good to merge

2024-07-10 12:14 UTC, danoli3 approved these changes

2024-07-10 13:23 UTC, merged

2024-07-10 16:04 UTC, ofTheo commented
Thanks @danoli3 ! 

The difference between the rects in the graphics example is because they are animated randomly. 

And the difference in the color rects example looks more to do with color differences between the programmable renderer and the legacy renderer ( though why that is I am not sure ). 

I am guessing neither are due to this PR though. 

The rect fitting example also uses random rects ( in red ) - so the delta is just that too